---
title: "Spotify Popularity Analysis"
format:
  html:
    self-contained: true
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(scales)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

rolling_stone <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-05-07/rolling_stone.csv')

rs2 <- rolling_stone|>
  filter(release_year >= 2016)|>
  mutate(clean_name = fct_reorder(clean_name, spotify_popularity, .desc = TRUE)) |>
  arrange(desc(spotify_popularity)) # Reorder by spotify popularity

ggplot(rs2, aes(x = spotify_popularity, y = clean_name)) + # Create lollipop graph
  geom_segment(aes(x = 0, xend = spotify_popularity, y = clean_name, yend = clean_name),
               linewidth = 1.2, color = "limegreen") +
  geom_point(size = 2.5, color = "limegreen") +
  labs(x = "Spotify Popularity", y = "Artist") + 
  labs(title ="Spotify artist popularity rankings by album (2016 to 2019)",
       subtitle = "The albums of Harry Styles, Billie Eilish, and Frank Ocean rank highest",
       caption = "Source: Rolling Stone
       
       Note: Spotify's popularity index is based on factors such as 
       play count, recency, total play share, user engagement, and skip rate") +
  theme_minimal() +
  theme(panel.grid.major = element_line(color = "lightgray", linewidth = 0.3),# Gridlines
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(), 
        plot.title = element_text(face= "bold"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_y_discrete(limits = rev(levels(rs2$clean_name))) # Reverse order

```

```{r, eval=FALSE}
rolling_stone <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-05-07/rolling_stone.csv')

rs2 <- rolling_stone |>
  filter(release_year >= 2016) |>
  mutate(clean_name = fct_reorder(clean_name, spotify_popularity, .desc = TRUE)) |>
  arrange(desc(spotify_popularity))

ggplot(rs2, aes(x = spotify_popularity, y = clean_name)) +
  geom_segment(aes(x = 0, xend = spotify_popularity, y = clean_name, yend = clean_name),
               linewidth = 1.2, color = "limegreen") +
  geom_point(size = 2.5, color = "limegreen") +
  labs(title ="Spotify artist popularity rankings by album (2016 to 2019)",
       subtitle = "The albums of Harry Styles, Billie Eilish, and Frank Ocean rank highest",
       caption = "Source: Rolling Stone

       Note: Spotify's popularity index is based on factors such as 
       play count, recency, total play share, user engagement, and skip rate") +
  theme_minimal() +
  theme(panel.grid.major = element_line(color = "lightgray", linewidth = 0.3),
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        plot.title = element_text(face= "bold"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_y_discrete(limits = rev(levels(rs2$clean_name)))
```
